import { useRef } from 'react'
import { addDays, compareDays, daysInMonth, formatIsoDay, isFuture, parseIsoDay, startOfMonth, weekdayOffset } from '../domain/dateUtils'
import type { IsoDate, Period } from '../types/period'

interface Props { month: IsoDate; periods: Period[]; today: IsoDate; predicted: IsoDate[]; preview?: { start: IsoDate; end: IsoDate }; onSelect(day: IsoDate): void; onRange(start: IsoDate, end: IsoDate): void; onRangePreview(preview?: { start: IsoDate; end: IsoDate }): void }
export function MonthGrid({ month, periods, today, predicted, preview, onSelect, onRange, onRangePreview }: Props) {
  const first = startOfMonth(month), days = daysInMonth(first), offset = weekdayOffset(first)
  const labels = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
  const drag = useRef<{ start: IsoDate; end: IsoDate; moved: boolean } | undefined>(undefined), suppressClick = useRef(false)
  const dayAtPointer = (event: React.PointerEvent<HTMLDivElement>): IsoDate | undefined => {
    const button = typeof document.elementFromPoint === 'function' ? document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLButtonElement>('button[data-day]') : undefined
    return button && !button.disabled ? button.dataset.day as IsoDate : undefined
  }
  const finishDrag = () => { const value = drag.current; drag.current = undefined; onRangePreview(undefined); if (value?.moved) { suppressClick.current = true; onRange(value.start, value.end) } }
  return <section className="month" aria-label={new Intl.DateTimeFormat('en', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(parseIsoDay(first))}><h2>{new Intl.DateTimeFormat('en', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(parseIsoDay(first))}</h2><div className="weekdays">{labels.map(label => <span key={label}>{label}</span>)}</div><div className="days" onPointerMove={event => { const day = dayAtPointer(event); if (drag.current && day && day !== drag.current.end) { drag.current.end = day; drag.current.moved = true; onRangePreview({ start: drag.current.start, end: day }) } }} onPointerUp={finishDrag} onPointerCancel={() => { drag.current = undefined; onRangePreview(undefined) }}>{Array.from({ length: offset }, (_, index) => <span key={`blank-${index}`} />)}{Array.from({ length: days }, (_, index) => { const day = addDays(first, index); const period = periods.find(item => day >= item.start && day <= item.end); const future = isFuture(day, today); const prediction = predicted.includes(day); const selected = preview && compareDays(day, preview.start < preview.end ? preview.start : preview.end) >= 0 && compareDays(day, preview.start < preview.end ? preview.end : preview.start) <= 0; return <button key={day} data-day={day} type="button" disabled={future} aria-label={`${formatIsoDay(parseIsoDay(day))}${period ? ', recorded period' : ''}${future ? ', future date' : ''}`} className={[period && 'marked', selected && 'selected', prediction && 'predicted', day === today && 'today'].filter(Boolean).join(' ')} onPointerDown={event => { if (event.button !== 0) return; drag.current = { start: day, end: day, moved: false }; onRangePreview({ start: day, end: day }); event.currentTarget.setPointerCapture?.(event.pointerId) }} onClick={() => { if (suppressClick.current) { suppressClick.current = false; return } onSelect(day) }}>{index + 1}</button> })}</div></section>
}
