import { useState } from 'react'
import type { PeriodDraft } from '../types/period'
import type { IsoDate } from '../types/period'
import { rangeIsValid } from '../domain/periodRules'

interface Props { draft: PeriodDraft; today: IsoDate; pending: boolean; error?: string; onSave(draft: PeriodDraft): void; onDelete?(id: string): void; onChangeDates?(): void; onCancel(): void }
export function PeriodEditor({ draft, today, pending, error, onSave, onDelete, onChangeDates, onCancel }: Props) {
  const [value, setValue] = useState(draft), [confirming, setConfirming] = useState(false)
  const validation = rangeIsValid(value.start, value.end, today) || (value.comment.length > 2000 ? 'Comment must be 2,000 characters or fewer.' : undefined)
  return <div className="dialog-backdrop" role="presentation"><section className="editor" role="dialog" aria-modal="true" aria-labelledby="editor-title"><h2 id="editor-title">{value.id ? 'Edit period' : value.merged ? 'Merge periods' : 'Add period'}</h2><label>Start<input type="date" max={today} value={value.start} onChange={event => setValue({ ...value, start: event.target.value as IsoDate })}/></label><label>End<input type="date" max={today} value={value.end} onChange={event => setValue({ ...value, end: event.target.value as IsoDate })}/></label>{value.merged && <p className="hint">Touching or overlapping periods will be merged. Review the combined note before saving.</p>}<label>Comment (optional)<textarea maxLength={2001} value={value.comment} onChange={event => setValue({ ...value, comment: event.target.value })}/></label>{(validation || error) && <p role="alert">{validation || error}</p>}<div className="actions"><button type="button" onClick={onCancel} disabled={pending}>Cancel</button>{onChangeDates && <button type="button" onClick={onChangeDates} disabled={pending}>Change dates</button>}<button type="button" onClick={() => onSave(value)} disabled={pending || Boolean(validation)}>Save</button></div>{value.id && onDelete && <div className="delete"><button type="button" onClick={() => setConfirming(!confirming)} disabled={pending}>Delete period</button>{confirming && <span><button type="button" onClick={() => onDelete(value.id!)} disabled={pending}>Confirm delete</button><button type="button" onClick={() => setConfirming(false)} disabled={pending}>Keep period</button></span>}</div>}</section></div>
}
